mutation_count = mutation_simulator(gene_number = 20000,window_number=100,feature_prob = 0.2,base_rate = 2e-6,sample_size = 314, p_risk = 1, effect_size = 1.5)
head

mutation_count = mutation_simulator_v2(gene_number = 500,window_number=1000,feature_prob = 0.2,base_rate = 2e-6,sample_size = 314, p_risk = 0.3, effect_size = 3)

# This function estimates the relative risk from simulated data generated by mutation_simulator_v2

estimate_effect_size_for_simulation_data_mixture_with_categorization<-function(data,feature_start = 5, feature_end = 6, feature_number = 2, prior_prob = 0.3){
  #[data] is the returned value from function{mutation_simulator}
  #[feature_start] is the column number of the first feature in data$data
  #[feature_end] is the column number of the last feature in data$data
  #[feature_number] is the number of features
  #[prior_prob] is the prior probability of each gene being a risk gene. For simplicity, set to be equal for all genes, and is eual to the prior probability used in mutation_simulator_v2

  # first get the real mutation rate by multiplying 2 and sample size.
  data$data$base_mut_rate = data$data$base_mut_rate * data$sample_size *2
  
  partition_by_gene <- split(data$data, data$data$gene)
  # function to get effective information of each element of partition_by_gene
  # These information are those necessary to compute log-likelihood in the optimization function
  partition_feature <- function(pbg){
    # input is one element of the list of partition_by_gene
    pbg_split <- split(pbg, pbg[,feature_start:feature_end],drop = TRUE)
    info_for_each_feature <- function(feature_set){
      list(feature_vector = as.numeric(feature_set[1,feature_start:feature_end]), sum_mut_rate_count = sum(feature_set[,3]*log(feature_set[,4])), sum_mut_rate = sum(feature_set[,4]), sum_mut_count = sum(feature_set[,3]), log_fcount = sum(log(factorial(feature_set[,3]))))
    }
    sapply(pbg_split, info_for_each_feature,simplify = FALSE)
  }
  data_partition <- sapply(partition_by_gene, partition_feature, simplify = FALSE)
  
  fr<-function(x){
    all_rr = x
    cal_logP_Zg1 <- function(data_partition_element){
      cal_logP_Zg1_level2 <-function(data_partition_element_level2){
        data_partition_element_level2[[2]]+data_partition_element_level2[[4]]*data_partition_element_level2[[1]]%*%all_rr-data_partition_element_level2[[3]]*exp(data_partition_element_level2[[1]]%*%all_rr)-data_partition_element_level2[[5]]
      }
      sum(sapply(data_partition_element, cal_logP_Zg1_level2))
    }
    
    cal_logP_Zg0 <- function(data_partition_element){
      cal_logP_Zg0_level2 <-function(data_partition_element_level2){
        data_partition_element_level2[[2]]-data_partition_element_level2[[3]]-data_partition_element_level2[[5]]
      }
      sum(sapply(data_partition_element, cal_logP_Zg0_level2))
    }
    
    logP_Zg1 = sapply(data_partition, cal_logP_Zg1)
    logP_Zg0 = sapply(data_partition, cal_logP_Zg0)
    sum(log((prior_prob*exp(logP_Zg1)+(1-prior_prob)*exp(logP_Zg0))))
  }
  optimization_time <- system.time(mle <- optim(rep(0.1, feature_number), fr,control=list("fnscale"=-1), hessian = TRUE))
  list(optimization_time = optimization_time,mle = mle)
}

# This function estimates the relative risk from simulated data generated by mutation_simulator_v2

estimate_effect_size_for_simulation_data_mixture_without_categorization<-function(data, feature_start = 5, feature_end = 6, feature_number = 2, prior_prob = 0.3){
  #[data] is the returned value from function{mutation_simulator}
  #[feature_start] is the column number of the first feature in data$data
  #[feature_end] is the column number of the last feature in data$data
  #[feature_number] is the number of features
  #[prior_prob] is the prior probability of each gene being a risk gene. For simplicity, set to be equal for all genes, and is eual to the prior probability used in mutation_simulator_v2
  # first get the real mutation rate by multiplying 2 and sample size.
  data$data$base_mut_rate = data$data$base_mut_rate * data$sample_size *2
  fr<-function(x){
    all_rr <- x
    logP_Zg1 <- by(data$data, data$data[,"gene"],  
                  function(x) sum(x$mut_count*(log(x$base_mut_rate)+(as.matrix(x[,feature_start:feature_end])%*%all_rr))-x$base_mut_rate*exp((as.matrix(x[,feature_start:feature_end])%*%all_rr))-log(factorial(x$mut_count))))
    logP_Zg0 <- by(data$data, data$data[,"gene"],
                  function(x) sum(x$mut_count*log(x$base_mut_rate)-x$base_mut_rate-log(factorial(x$mut_count))))
    sum(log((prior_prob*exp(logP_Zg1)+(1-prior_prob)*exp(logP_Zg0)))) # minimization
  }
  optimization_time <- system.time(mle <- optim(rep(0.1, feature_number), fr,control=list("fnscale"=-1), hessian = TRUE))
  list(optimization_time = optimization_time,mle = mle)
}