---
title: "simulation of regulatory SNVs"
output: html_document
---

Use Noonan Brain + Roadmap as is used in the paper, Partition of enhancers using within distance strict cutoff. 
```{r}
all_genes_10kb_de_mutation_rate_SNV = read.delim("../other_annotation/mutation_rate/Noonan_brain_roadmap_union.promoter_plus_10kb_yanyu_pipeline.mutrate",
                                                 header = TRUE, sep = "\t", stringsAsFactors = FALSE)
```

Read in a mutation file, choosing which shouldn't matter for now, just in order to successfully load the subsequent R library. 
```{r}
#read in workspace that has unique mutation information
mutation = new.env()
load("../data/161026_Filtered_Stephen_Scherer_Gemomic_Medicine_ASD_de_novo_SNVs_germline_with_NC_control_data_matrixtransformed_for_old_code.Rdata", envir = mutation)
```

### simulation based on smapling mutations

```{r,echo=FALSE}
source("../lib/160930_screen_burden_functions_test_more_genelist_focused.R")

get_number <- function(x){length(x[x>0])}

sim_mutation_in_geneset <- function(mutrate, geneset, sim_times = 100, observed, total_mut){
  temp = rmultinom(sim_times,total_mut, mutrate[,2]/sum(mutrate[,2]))
  rownames(temp) = mutrate[,1]
  temp = temp[is.element(rownames(temp),geneset),]
  sum = apply(temp, 2, sum)
  pvalue = length(sum[sum>=observed])/sim_times
  list(pvalue = pvalue, observed_mutations = observed, ave_mutations_in_genesets = mean(sum), distribution = sum)
}
```

### Manuscript data
```{r, cache=TRUE, dependson=sim_mutation_in_geneset}
set.seed(123)
#stringent ASD
#sim_mutation_in_geneset(all_genes_10kb_de_mutation_rate_SNV, stringent_ASD, 10000, 16, 408)
# putative ASD
temp = sim_mutation_in_geneset(all_genes_10kb_de_mutation_rate_SNV, relaxed_ASD, 10000, 91, 361)
temp[c("pvalue", "observed_mutations", "ave_mutations_in_genesets")]
#temp["distribution"]
hist(as.numeric(temp[["distribution"]]))
#constrained/haploinsufficient
#sim_mutation_in_geneset(all_genes_10kb_de_mutation_rate_SNV, constraint_union, 10000, 69, 408)

```

### Scherer data
```{r, cache=TRUE, dependson=sim_mutation_in_geneset}
#stringent ASD
#sim_mutation_in_geneset(all_genes_10kb_de_mutation_rate_SNV, stringent_ASD, 10000, 16, 408)
# putative ASD
temp = sim_mutation_in_geneset(all_genes_10kb_de_mutation_rate_SNV, relaxed_ASD, 10000, 46, 166)
temp[c("pvalue", "observed_mutations", "ave_mutations_in_genesets")]
#temp["distribution"]
hist(as.numeric(temp[["distribution"]]))
#constrained/haploinsufficient
#sim_mutation_in_geneset(all_genes_10kb_de_mutation_rate_SNV, constraint_union, 10000, 69, 408)

```


