
##### combine promoter and enhancer together for estimating relative risk


##### top 6% TADA genes for fitting the 50bp-window model: estimate relative risk

```{r,echo=FALSE}
load("161229_estimate_effect_with_three_epi_and_one_conservation_1bp_overlap_top_6_pct_tada_using_synony_only_for_ASD_coding.Rdata")
fisher_info<-solve(-ASD_model_manuscript$mle$hessian)
prop_sigma<-sqrt(diag(fisher_info))
upper<-ASD_model_manuscript$mle$par+1.96*prop_sigma
lower<-ASD_model_manuscript$mle$par-1.96*prop_sigma
a = data.frame(relative_risk = ASD_model_manuscript$mle$par, lower_bound = lower, upper_bournd = upper)
rownames(a) = c("Noonan+Roadmap Brain H3K27ac", "Roadmap brain DHS", "ENCODE brain DHS","Phastcons100way")
knitr::kable(a)
```

##### top 6% TADA genes for fitting the 50bp-window model: mutation rate adjustment
```{r,echo=FALSE}
knitr::kable(ASD_model_manuscript$regression_coef)
```

##### all TADA genes for fitting the 50bp-window model: estimate relative risk

```{r,echo=FALSE}
load("161229_estimate_effect_with_three_epi_and_one_conservation_1bp_overlap_all_tada_using_synony_only_for_ASD_coding.Rdata")
fisher_info<-solve(-ASD_model_manuscript$mle$hessian)
prop_sigma<-sqrt(diag(fisher_info))
upper<-ASD_model_manuscript$mle$par+1.96*prop_sigma
lower<-ASD_model_manuscript$mle$par-1.96*prop_sigma
a = data.frame(relative_risk = ASD_model_manuscript$mle$par, lower_bound = lower, upper_bournd = upper)
rownames(a) = c("Noonan+Roadmap Brain H3K27ac", "Roadmap brain DHS", "ENCODE brain DHS","Phastcons100way")
knitr::kable(a)
```

##### all TADA genes for fitting the 50bp-window model: mutation rate adjustment
```{r,echo=FALSE}
knitr::kable(ASD_model_manuscript$regression_coef)
```
