```{r}
set.seed(100)
source("../lib/170122_base_level_simulation_functions.R")
```

##### base-level simulation and optimization of mutation rate adjustion parameters using optim() without categorization
```
Assume 2 binary variables (e.g., epigenomic annotations) affect the mutational rate of risk genes.
Assume the mutation rate has already been adjusted for.

```

##### generate a dataset with 100base/gene, 500 genes, effect size 2
```{r, cache = TRUE, cache.extra = estimate_effect_size_for_simulation_data_mixture_with_categorization, cache.extra = mutation_simulator_v2}
mutation_count <- mutation_simulator_v2(gene_number = 500,window_number=100,feature_prob = 0.2,base_rate = 2e-6,sample_size = 314, p_risk = 0.3, effect_size = 2)
cate <- estimate_effect_size_for_simulation_data_mixture_with_categorization(mutation_count)
noncate <- estimate_effect_size_for_simulation_data_mixture_without_categorization(mutation_count)
```

```{r}
cate
noncate
```

##### generate a dataset with 10000base/gene, 500 genes, effect size 2
```{r, cache=TRUE, cache.extra = estimate_effect_size_for_simulation_data_mixture_with_categorization, cache.extra = mutation_simulator_v2}
mutation_count <- mutation_simulator_v2(gene_number = 500,window_number=10000,feature_prob = 0.2,base_rate = 2e-6,sample_size = 314, p_risk = 0.3, effect_size = 2)
cate <- estimate_effect_size_for_simulation_data_mixture_with_categorization(mutation_count)
noncate <- estimate_effect_size_for_simulation_data_mixture_without_categorization(mutation_count)
```

```{r}
cate
noncate
dim(mutation_count$data)
rm(mutation_count)
```

##### generate a dataset with 10000base/gene, 5000 genes, effect size 2
```{r, cache=TRUE, cache.extra = estimate_effect_size_for_simulation_data_mixture_with_categorization, cache.extra = mutation_simulator_v2}
mutation_count <- mutation_simulator_v2(gene_number = 5000,window_number=10000,feature_prob = 0.2,base_rate = 2e-6,sample_size = 314, p_risk = 0.3, effect_size = 2)
cate <- estimate_effect_size_for_simulation_data_mixture_with_categorization(mutation_count)
#noncate <- estimate_effect_size_for_simulation_data_mixture_without_categorization(mutation_count)
```

```{r}
cate
#noncate
dim(mutation_count$data)
rm(mutation_count)
```


##### generate a dataset with 10000base/gene, 18000 genes, effect size 2
```{r, cache=TRUE, cache.extra = estimate_effect_size_for_simulation_data_mixture_with_categorization, cache.extra = mutation_simulator_v2}
mutation_count <- mutation_simulator_v2(gene_number = 18000,window_number=10000,feature_prob = 0.2,base_rate = 2e-6,sample_size = 314, p_risk = 0.3, effect_size = 2)
cate <- estimate_effect_size_for_simulation_data_mixture_with_categorization(mutation_count)
#noncate <- estimate_effect_size_for_simulation_data_mixture_without_categorization(mutation_count)
```

```{r}
cate
#noncate
dim(mutation_count$data)
rm(mutation_count)
```

